# Generated by Django 5.0.8 on 2024-08-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_todo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
